# ==============================================================================
# HYPRIDLE CONFIGURATION
# ==============================================================================

general {
    lock_cmd = pidof hyprlock || hyprlock       # dbus/sysd lock command
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display
}

# Dim screen after 5 minutes
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 30%       # set monitor backlight to minimum
    on-resume = brightnessctl -r                # restore monitor backlight
}

# Lock screen after 10 minutes
listener {
    timeout = 600
    on-timeout = loginctl lock-session          # lock screen
}

# Suspend after 15 minutes
listener {
    timeout = 900
    on-timeout = systemctl suspend              # suspend pc
}
